# Generated by Django 3.1.4 on 2021-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailID', models.CharField(max_length=100)),
                ('engineer_group', models.CharField(max_length=100)),
            ],
        ),
    ]
