# Generated by Django 3.1.4 on 2021-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210706_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
