# Generated by Django 3.1.4 on 2021-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210706_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='assigned_engineer',
            field=models.CharField(default='Shashi', max_length=100),
        ),
    ]
