# Generated by Django 3.1.4 on 2021-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210711_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='assignment_group',
            field=models.CharField(choices=[('HelpDesk', 'HelpDesk'), ('ITSecAdmin', 'ITSecAdmin'), ('Operations', 'Operations'), ('Network', 'Network'), ('Infrastructure', 'Infrastructure')], default='HelpDesk', max_length=20),
        ),
    ]
