# Generated by Django 3.1.4 on 2021-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_tickets_assignment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='submitted_by',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
