# Generated by Django 3.1.4 on 2021-09-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tickets_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='comments',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
